[package]
name = "rust-num-guess"
version = "0.1.0"
authors = ["monokemonoke kawabataryuhei@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"
